### ISSUE TITLE
Default Behavior is Polling

### ISSUE THREAD

**Issue by truell20** [joshuagruenstein/snooze#11]
Pipes should not poll by default. While useful in some cases, this is not what the plurality of cases warrants.

**Comment by joshuagruenstein** [comment]
I think URL and Function pipes should not poll by default, however objects should.  There are minimal disadvantages to this, and it seems to be what users might expect (when they update the value, the DOM updates as well).  Thoughts @truell20?

**Comment by joshuagruenstein** [comment]
Fixed this as discussed in my previous comment in 946dad0bf6b3a5d8774548f74e5b446674dc6592.  No default polling for URLs and functions, and 0.3 second polling for objects.
